import asyncio
import json
from typing import Protocol

import aiohttp
from loguru import logger


class LLMError(Exception):
    """Кастомная ошибка для проблем с LLM."""

    pass


class LLMClient(Protocol):
    """Протокол (интерфейс), которому должны следовать все клиенты LLM."""

    async def generate_code_options(self, context: str) -> list[str]: ...

    async def finalize_code(self, context: str) -> str: ...


class OpenAIClient:
    """
    Реализация клиента для OpenAI-совместимых API (OpenAI, Groq, etc.).
    """

    def __init__(self, api_key: str, api_base: str):
        self.api_key = api_key
        self.api_base = api_base
        self.prompt_template = (
            "You are a Python code generation assistant. "
            "Given the existing code context, generate 4 syntactically correct and logical options for the VERY"
            " NEXT line of code. "
            "Each option must be a single line, no longer than 95 characters. "
            "Do not add any comments or explanations. "
            "Return the response as a JSON array of strings.\n\n"
            "Existing code context:\n"
            "```python\n{context}\n```\n\n"
            "Provide 4 options for the next line of code:"
        )

    async def generate_code_options(self, context: str) -> list[str]:
        prompt = self.prompt_template.format(context=context or "# No code yet.")
        headers = {"Authorization": f"Bearer {self.api_key}"}
        payload = {
            "model": "llama3-8b-8192",  # Модель от Groq, как самый быстрый вариант
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.7,
        }
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(f"{self.api_base}/chat/completions", headers=headers, json=payload) as resp:
                    if resp.status != 200:
                        error_text = await resp.text()
                        logger.error(f"LLM API request failed with status {resp.status}: {error_text}")
                        raise LLMError(f"API request failed: {error_text}")
                    response_data = await resp.json()
                    content_str = response_data["choices"][0]["message"]["content"]
                    return json.loads(content_str)
        except (aiohttp.ClientError, json.JSONDecodeError, KeyError, IndexError) as e:
            logger.exception("An error occurred during LLM request")
            raise LLMError(f"Failed to process LLM response: {e}") from e


class MockLLMClient:
    """
    Фейковый клиент-заглушка для демонстрации и отладки.
    Имитирует работу OpenAI-совместимого клиента.
    """

    def __init__(self, *args, **kwargs):
        logger.warning("=" * 50)
        logger.warning("INITIALIZING MOCK LLM CLIENT. NO REAL API REQUESTS WILL BE SENT.")
        logger.warning("=" * 50)
        self.options = ["import os", "import sys", "from typing import List", "print('Hello, world!')"]

    async def generate_code_options(self, context: str) -> list[str]:
        await asyncio.sleep(1)  # Имитация сетевой задержки
        logger.info(f"MockLLMClient: Faking generation for context:\n---\n{context or 'Empty context'}\n---")
        return self.options

    async def finalize_code(self, context: str) -> str:
        await asyncio.sleep(1)  # Имитация работы
        logger.info("MockLLMClient: Faking code finalization.")

        final_code = (
            "# This code was collaboratively generated by a bot\n\n"
            f"{context}\n\n"
            'if __name__ == "__main__":\n'
            "    print('Execution finished.')\n"
        )
        return final_code
